apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cyberambassador.fullname" . }}
  namespace: {{ include "cyberambassador.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    checksum/config: {{ include (print $.Template.BasePath "/config-secrets/config.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/config-secrets/sealed-secret.yaml") . | sha256sum }}
  labels:
    app: {{ include "cyberambassador.fullname" . }}

spec:
  serviceAccountName: {{ .Values.serviceAccount.name }}

  selector:
    matchLabels:
      app: {{ include "cyberambassador.fullname" . }}

  template:
    metadata:
      labels:
        app: {{ include "cyberambassador.fullname" . }}

    spec:
      securityContext:
        runAsUser: {{ .Values.application.podSecurityContext.runAsUser }}
        runAsGroup: {{ .Values.application.podSecurityContext.runAsGroup }}
        fsGroup: {{ .Values.application.podSecurityContext.fsGroup }}
        fsGroupChangePolicy: {{ .Values.application.podSecurityContext.fsGroupChangePolicy }}

      {{- if .Values.application.initContainer.enabled }}
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Postgres to be ready..."
              until nc -z {{ .Values.application.initContainer.postgresHost }} {{ .Values.application.initContainer.postgresPort }}; do
                echo "Postgres not ready yet, sleeping..."
                sleep 2
              done
              echo "Postgres is ready!"
      {{- end }}

      containers:
        - name: {{ .Values.application.name }}
          image: "{{ .Values.application.image.repository }}:{{ .Values.application.image.tag }}"
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.application.service.targetPort }}

          envFrom:
            - configMapRef:
                name: {{ .Values.application.envFrom.configMapName }}
            - secretRef:
                name: {{ .Values.application.envFrom.secretName }}

          securityContext:
            runAsNonRoot: {{ .Values.application.containerSecurityContext.runAsNonRoot }}
            allowPrivilegeEscalation: {{ .Values.application.containerSecurityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.application.containerSecurityContext.readOnlyRootFilesystem }}
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          resources:
            {{- toYaml .Values.application.resources | nindent 12 }}

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}
