{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Values.namespace }}

spec:
  type: ClusterIP
  selector:
    app: {{ .Values.database.name }}

  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
{{- end }}
