{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "cyberambassador.fullname" . }}-http-redirect
  namespace: {{ .Values.gateway.gatewayNamespace }}

spec:
  parentRefs:
    - name: {{ .Values.gateway.gatewayName }}
      namespace: {{ .Values.gateway.gatewayNamespace }}
      sectionName: {{ .Values.gateway.httpSectionName }}

  hostnames:
    - {{ .Values.gateway.host }}

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
{{- end }}
